import mv3d from './mv3d.js';

mv3d.blendModes={
	[PIXI.BLEND_MODES.NORMAL]: BABYLON.Engine.ALPHA_COMBINE,
	[PIXI.BLEND_MODES.ADD]: BABYLON.Engine.ALPHA_ADD,
	[PIXI.BLEND_MODES.MULTIPLY]: BABYLON.Engine.ALPHA_MULTIPLY,
	[PIXI.BLEND_MODES.SCREEN]: BABYLON.Engine.ALPHA_SCREENMODE,
	
};