import './mv3d.js';
import './mod_babylon.js';
import './mod_mv.js';
import './parameters.js';
import './blenders.js';
import './input.js';
import './configuration.js';
import './plugin_commands.js';
import './tileData.js'
import './loadMap.js';
import './assets.js';
import './characters.js';
import './movement.js';
import './parallax.js';